### ISSUE TITLE
Strange distribution of duration of outputted vocalisations

### ISSUE THREAD

**Issue by giodesp** [MarvinLvn/voice-type-classifier#30] opened 2023-06-14 09:49 UTC
Hi all,
This isn't so much a problem but it would be great to get any thoughts on why the following might happen.
Our group has found that when plotting the distribution of the duration of vocalisations output by the VTC, we see these strange periodic peaks in the distribution:
![image](https://github.com/MarvinLvn/voice-type-classifier/assets/112628014/b8a527e7-b938-43ca-bf78-ccbc145338ca)
This particular plot is from one of the RTTMs produced by the VTC. But we have found the same when plotting from our own processing of the .npy arrays and on different datasets. I'd be really interested to get any thoughts on this or to hear if it's a common issue.

**Comment by MarvinLvn** [comment] 2023-06-16 09:02
Hi @giodesp,

I want to start by saying that we also observed this behaviour on our data! These periodic peaks, with a period of 500ms, are not the result of how you apply the model or artefacts caused by your audio files :)

They're an artefact of how pyannote handles the inference process. Briefly, the steps can be described as follows:
1) We apply a sliding window (2s-long window, shifted every **500ms**) so as to get multiple speech probabilities per frame
2) We apply a Hamming window to smooth out the average of the many probabilities computed in step 1).
3) We apply a threshold to decide whether the class of interest (e.g., KCHI) is activated or not.

There's a bug in step 2), which would cause the model to more likely return segments whose duration is 500ms, 1s, 1.5s, 2s, etc.
If you're interested in detecting when a given class is activated in the audio, these peaks will likely not affect your analysis.
If you're interested in post-processing the detected segments, then you might end up with segments that are slightly shorter or longer than they should be.   
 
More details in @hbredin's paper to appear in the next Interspeech conference. 
This bug will be fixed at some point, but it's hard to tell you when exactly!

**Comment by giodesp** [comment] 2023-06-16 09:22
Hi Marvin,
Thanks so much for your explanation. I'm relieved to hear nothing amiss is happening in our application of the classifier or our microphones! 
I don't think anyone using the vtc output from our group will be doing analysis of vocalisation durations in a way that would be affected too much by the bug. Thanks again for this great tool and I look forward to the next paper.
Gio

**Comment by MarvinLvn** [comment] 2023-06-16 09:24
Thank you for your kind words! 
All credit goes to @hbredin !

**Closed as completed** 2023-06-19 17:06 UTC
